/**
 * Provider contracts for trend and source collection.
 *
 * This module is intentionally API-client agnostic: it does not call Naver,
 * YouTube, public medical APIs, MCP servers, Supabase, or n8n. It only defines
 * the normalized boundary that n8n/AI Agent collectors can use before creating
 * content-platform Topic and Source candidates.
 */

import type {
  EntityId,
  IsoDateTime,
  JsonValue,
  SourceTrustLevel,
  SourceType,
  SourceVerificationStatus,
} from "./content-platform";

export type CollectionProviderId =
  | "naver-datalab"
  | "youtube-data-api"
  | "official-medical-public-source"
  | "web-search-api"
  | "mcp-search";

export type CollectionProviderKind = "trend" | "source" | "hybrid";

export type CollectionProviderCapability =
  | "trend:collect"
  | "topic:candidate:discover"
  | "source:candidate:discover"
  | "source:trusted:discover"
  | "source:video:discover"
  | "raw:metadata:preserve";

export type CollectionProviderAuthType = "none" | "api_key" | "oauth" | "client_id_secret" | "mcp";

export type CollectionProvider = {
  id: CollectionProviderId;
  label: string;
  kind: CollectionProviderKind;
  capabilities: CollectionProviderCapability[];
  authType: CollectionProviderAuthType;
  defaultLocale?: string;
  defaultCountry?: string;
  /**
   * Human-readable note for setup constraints. Actual secrets belong in the
   * future runtime configuration, never in this contract.
   */
  setupNote?: string;
};

export type CollectionWindow = {
  startDate: string;
  endDate: string;
  timeUnit: "hour" | "date" | "week" | "month";
};

export type CollectionRequest = {
  providerId: CollectionProviderId;
  siteId: EntityId;
  locale: string;
  country: string;
  collectedBy: "n8n" | "ai_agent" | "human" | "system";
  requestedAt: IsoDateTime;
  window?: CollectionWindow;
  seedKeywords?: string[];
  topicId?: EntityId;
  maxResults?: number;
  /**
   * Provider-specific knobs such as device, gender, age group, regionCode,
   * relevanceLanguage, channelId, or official agency category.
   */
  providerOptions?: Record<string, JsonValue>;
};

export type ProviderRawMetadata = {
  /**
   * Keep a small, serializable snapshot of the provider response for audit and
   * replay. Large bodies or copyrighted full text should be stored elsewhere
   * and referenced by location.
   */
  preserved: boolean;
  responseHash?: string;
  rawPayload?: JsonValue;
  rawPayloadLocation?: string;
  termsOfUseNote?: string;
};

export type ExternalDuplicateKey = {
  providerId: CollectionProviderId;
  /**
   * Preferred stable external id. Examples: Naver keyword group id generated by
   * our collector, YouTube video id, official article/page id, public data id.
   */
  externalId?: string;
  /**
   * URL-based fallback for pages and videos. Canonicalized before storage by a
   * future service layer.
   */
  sourceUrl?: string;
  /**
   * Hash fallback for sources without stable ids or canonical URLs.
   */
  contentHash?: string;
};

export type NormalizedTrendCandidate = {
  providerId: CollectionProviderId;
  siteId: EntityId;
  externalKey: ExternalDuplicateKey;
  label: string;
  normalizedKeyword: string;
  relatedKeywords: string[];
  locale: string;
  country: string;
  window: CollectionWindow;
  collectedAt: IsoDateTime;
  /**
   * Provider-normalized score, not a universal absolute search volume.
   */
  score: number;
  scoreUnit: "relative_interest" | "rank" | "mention_count" | "provider_score";
  changeRate?: number;
  rawMetadata: ProviderRawMetadata;
  /**
   * Maps to Topic candidate creation in the content platform. This is not a
   * Topic record yet and must be reviewed/deduplicated by a service layer.
   */
  suggestedTopic: {
    name: string;
    slug?: string;
    topicType: string;
    keywords: string[];
    trendScore?: number;
  };
};

export type NormalizedSourceCandidate = {
  providerId: CollectionProviderId;
  siteId?: EntityId;
  externalKey: ExternalDuplicateKey;
  sourceUrl: string;
  canonicalUrl?: string;
  title: string;
  publisherName: string;
  sourceType: SourceType;
  language: string;
  locale?: string;
  country?: string;
  publishedAt?: IsoDateTime;
  retrievedAt: IsoDateTime;
  summary?: string;
  trustLevel: SourceTrustLevel;
  verificationStatus: SourceVerificationStatus;
  rawMetadata: ProviderRawMetadata;
  /**
   * Maps to a future Source candidate. It is intentionally not a Source record
   * yet because URL canonicalization, trust review, and duplicate detection
   * belong in the service/repository layer.
   */
  suggestedSource: {
    sourceType: SourceType;
    publisherName: string;
    title: string;
    canonicalUrl: string;
    language: string;
    trustLevel: SourceTrustLevel;
    verificationStatus: SourceVerificationStatus;
    contentHash?: string;
    metadata?: Record<string, JsonValue>;
  };
};

export type ProviderErrorCode =
  | "PROVIDER_UNAVAILABLE"
  | "AUTHENTICATION_FAILED"
  | "RATE_LIMITED"
  | "QUOTA_EXCEEDED"
  | "INVALID_REQUEST"
  | "UNSUPPORTED_CAPABILITY"
  | "PARSING_FAILED"
  | "TERMS_RESTRICTED"
  | "UNKNOWN_PROVIDER_ERROR";

export type ProviderError = {
  providerId: CollectionProviderId;
  code: ProviderErrorCode;
  message: string;
  retryable: boolean;
  occurredAt: IsoDateTime;
  httpStatus?: number;
  retryAfterSeconds?: number;
  rawMetadata?: ProviderRawMetadata;
};

export type ProviderResult<T> =
  | {
      ok: true;
      providerId: CollectionProviderId;
      collectedAt: IsoDateTime;
      data: T[];
      rawMetadata?: ProviderRawMetadata;
    }
  | {
      ok: false;
      providerId: CollectionProviderId;
      error: ProviderError;
    };

export type TrendProvider = CollectionProvider & {
  kind: "trend" | "hybrid";
  capabilities: Array<
    Extract<
      CollectionProviderCapability,
      "trend:collect" | "topic:candidate:discover" | "source:candidate:discover" | "source:video:discover" | "raw:metadata:preserve"
    >
  >;
};

export type SourceProvider = CollectionProvider & {
  kind: "source" | "hybrid";
  capabilities: Array<
    Extract<
      CollectionProviderCapability,
      | "source:candidate:discover"
      | "source:trusted:discover"
      | "source:video:discover"
      | "topic:candidate:discover"
      | "raw:metadata:preserve"
    >
  >;
};

export type HybridCollectionProvider = CollectionProvider & {
  kind: "hybrid";
};

export const NAVER_DATALAB_PROVIDER: TrendProvider = {
  id: "naver-datalab",
  label: "Naver DataLab",
  kind: "trend",
  capabilities: ["trend:collect", "topic:candidate:discover", "raw:metadata:preserve"],
  authType: "client_id_secret",
  defaultLocale: "ko-KR",
  defaultCountry: "KR",
  setupNote: "Requires Naver developer application Client ID and Client Secret.",
};

export const YOUTUBE_DATA_API_PROVIDER: HybridCollectionProvider = {
  id: "youtube-data-api",
  label: "YouTube Data API",
  kind: "hybrid",
  capabilities: [
    "trend:collect",
    "topic:candidate:discover",
    "source:candidate:discover",
    "source:video:discover",
    "raw:metadata:preserve",
  ],
  authType: "api_key",
  defaultLocale: "ko-KR",
  defaultCountry: "KR",
  setupNote: "Requires a Google Cloud API key with YouTube Data API enabled.",
};

export const OFFICIAL_MEDICAL_PUBLIC_SOURCE_PROVIDER: SourceProvider = {
  id: "official-medical-public-source",
  label: "Official medical and public health sources",
  kind: "source",
  capabilities: ["source:candidate:discover", "source:trusted:discover", "raw:metadata:preserve"],
  authType: "none",
  defaultLocale: "ko-KR",
  defaultCountry: "KR",
  setupNote: "Some public APIs may require a service key, but the provider contract does not store it.",
};

export const INITIAL_HEALTH_KNOWHOW_COLLECTION_PROVIDERS = [
  NAVER_DATALAB_PROVIDER,
  YOUTUBE_DATA_API_PROVIDER,
  OFFICIAL_MEDICAL_PUBLIC_SOURCE_PROVIDER,
] as const;

export function providerSupports(
  provider: CollectionProvider,
  capability: CollectionProviderCapability,
): boolean {
  return provider.capabilities.includes(capability);
}
