create table if not exists public.published_contents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  queue_id bigint,
  publication_id bigint not null unique,
  content_id bigint not null,
  title text not null,
  slug text not null unique,
  publishing_package jsonb not null,
  request_fingerprint text not null,
  publish_status text not null default 'published',
  published_at timestamptz not null default now(),
  published_by text,
  source text not null default 'n8n',
  constraint published_contents_queue_id_check
    check (queue_id is null or queue_id >= 1),
  constraint published_contents_publication_id_check
    check (publication_id >= 1),
  constraint published_contents_content_id_check
    check (content_id >= 1),
  constraint published_contents_title_not_blank_check
    check (length(trim(title)) > 0),
  constraint published_contents_publish_status_check
    check (publish_status in ('published', 'failed', 'archived')),
  constraint published_contents_slug_format_check
    check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint published_contents_request_fingerprint_format_check
    check (request_fingerprint ~ '^[a-f0-9]{64}$'),
  constraint published_contents_publishing_package_object_check
    check (jsonb_typeof(publishing_package) = 'object')
);

create index if not exists published_contents_content_id_idx
  on public.published_contents(content_id);

create or replace function public.set_published_contents_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists published_contents_set_updated_at on public.published_contents;

create trigger published_contents_set_updated_at
before update on public.published_contents
for each row
execute function public.set_published_contents_updated_at();

alter table public.published_contents enable row level security;

revoke insert, update, delete on public.published_contents from anon, authenticated;

grant select, insert, update
on table public.published_contents
to service_role;

grant usage, select
on sequence public.published_contents_id_seq
to service_role;
